namespace Project_B.CodeServerSide.BrokerProvider.Helper.Configuration {
    public enum SectionName : short {
        AaundefinedDefault = 0,

        //Url Reserve from 1 to 999
        Domain = 1,
        UrlLiveTarget = 2,
        UrlOddsTarget = 3,
        UrlResultTarget = 4,
        UrlKab = 5,

        //StringFaviconTarget = 50,

        SimpleStringUserAgent = 901,

        //XPath Reserve from 1000 to 9999
        XPathToCategoryContainer = 1000,
        XPathToCategoryName = 1001,
        XPathToListCompetitionInCategory = 1002,
        XPathToCompetitionName = 1003,
        XPathToEventInList = 1004,
        XPathToOddsCompetitors = 1005,
        //XPathToOddsLiveResult = 1007,
        XPathToOddsFactor = 1008,
        XPathToEventResult = 1009,
        XPathToCompetitors = 1010,
        XPathToDate = 1011,
        XPathToResultValue = 1012,
        XPathToOddsConfirmation = 1013,

        //StringSimple Reserve from 10000 to 14999
        // = 10000,
        StringDateQueryFormat = 10001,
        StringMapStringsOddsParamJoin = 10002,
        StringMapStringsResultsParamJoin = 10003,
        StringOddConfirmation = 10004,
        StringOddBrokerID = 10005,
        StringOddCompetitorsShortName = 10006,
        StringMatchRow = 10007,
        StringCompetitionRow = 10008,
        StringCompetitionIDQuery = 10009,

        //Array Reserve from 15000 to 19999
        ArrayCompetitorSplitter = 15000,
        ArrayCookie = 15001,
        ArrayProxy = 15002,
        ArrayDateTimeFormat = 15003,
        //ArrayBadStartCompetitor = 15004,
        ArrayBadNameCompetitor = 15005,
        ArrayAddParamOdds = 15006,

        //Map Reserve from 30000 to Max
        MapStringsOddsParam = 30000,
        MapStringsResultsParam = 30001,
        MapStringsLanguageUrlParam = 30002,

        //Max value, helps improve autogenerated values without const number
        ZZzReservedLast = short.MaxValue,
    }
}